apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp.config
  namespace: webapp
data:
  s3.bucket: {{.bucket}}
  webapp.domain: {{.domain}}
  webapp.environment: {{.webappenvironment}}
  newrelic.browserId: {{quote .newrelicbrowserid}}
  newrelic.app_name: {{quote .newrelicappname}}
  site.conf: |-
    # Nginx for webapp
    server {
        server_name *.{{.domain}};

        listen 80;

        location / {
            error_page 418 = @proxy_to_app;
            return 418;
        }
        location @proxy_to_app {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            if ($http_x_forwarded_proto != "https") {
                rewrite ^ https://$host$request_uri? permanent;
            }
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://localhost:2000;
        }
        access_log /dev/stdout;
    }
