apiVersion: v1
kind: Secret
metadata:
  name: webapp.secret
  namespace: webapp
type: Opaque
data:
  webappemailkey: {{b64encode .emailkey}}
  pgpassword: {{b64encode .pgpassword}}
  pguser: {{b64encode .pguser}}
  pgdatabase: {{b64encode .pgdatabase}}
  pghost: {{b64encode .pghost}}
  newreliclicense: {{b64encode .newreliclicense}}
  encryptedkey: {{b64encode .encryptedkey}}
